# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('picture', models.FileField(blank=True, null=True, upload_to='users_pic')),
                ('email', models.CharField(max_length=1000)),
                ('Phone', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=2048)),
            ],
        ),
    ]
