# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20171010_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='CreditCard',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
