# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20171010_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='CreditCard',
            field=models.CharField(max_length=255),
        ),
    ]
