# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='short_massage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
